# must be unique in a given SonarQube instance
sonar.projectKey=gmv-bda:ai-service-ui
# this is the name and version displayed in the SonarQube UI. Was mandatory prior to SonarQube 6.1.
sonar.projectName=gmv-bda ai-service-ui
sonar.projectVersion=0.2.0.dev
 
# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# This property is optional if sonar.modules is set. 
sonar.sources=./ai_service_ui/ 

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

sonar.python.xunit.skipDetails=false
sonar.python.xunit.reportPath=build/test-reports/*.xml
sonar.python.coverage.reportPath=coverage.xml